name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Set up MSVC developer environment
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: x64

    # Build the Z80-Emu project
    - name: Build Project
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 Z80-Emu.sln

    # Zip the Release folder
    - name: Zip Release folder
      run: Compress-Archive -Path ./x64/Release/* -DestinationPath ./x64/Release/Z80-Emu.zip

    # Upload the zipped Release folder using v3
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-zip
        path: ./x64/Release/Z80-Emu.zip

    # Create a new GitHub release using the latest commit message as the body
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Z80 Emulator Release v1.0.${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}  # Use latest commit message as release body
        draft: false
        prerelease: false